### ISSUE TITLE
Consider removing Promises dependency in major version update

### ISSUE THREAD

**Issue by paulb777** [google/GoogleUtilities#107]
The Promises dependency is currently broken on macOS because it hasn't yet updated from a 10.10 minimum version.

On closer look, the dependency seems heavyweight for a single public API that is used in just one place in Firebase.

In Firebase:
```
$ git grep gul_dataTaskPromiseWithRequest
FirebaseAppCheck/Sources/Core/APIService/FIRAppCheckAPIService.m:  return [self.URLSession gul_dataTaskPromiseWithRequest:request]
FirebaseAppCheck/Tests/Unit/Core/FIRAppCheckAPIServiceTests.m:  OCMExpect([URLSessionMock gul_dataTaskPromiseWithRequest:URLRequestValidationArg])
```

**Comment by mdmathias** [comment]
Filed [an issue](https://github.com/google/promises/issues/209) on PromisesObjC.

**Comment by ncooke3** [comment]
Done via  #187. Will be released in v8.
