### ISSUE TITLE
iOS 17 New required reason API

### ISSUE THREAD

**Issue by lakshmankreditbee** [google/GoogleUtilities#128]
From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will GoogleUtilities sdk be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple about this issue?

**Comment by paulb777** [comment]
@lakshmankreditbee Thanks for the issue. We're investigating and plan to address later this fall.

**Comment by alarochelle** [comment]
Hi! Any news on this?

**Comment by paulb777** [comment]
Work in progress. It will be addressed along with https://github.com/firebase/firebase-ios-sdk/issues/11490. More details there.

**Comment by lakshmankreditbee** [comment]
Hi, when can we expect an update regarding this issue?

**Comment by lamdaniel** [comment]
I believe GoogleUtilities uses the required reason API's of:

- NSURLCreationDateKey
- NSUserDefaults

Can someone double check this for me?

**Comment by JLLA113** [comment]
Hi,

Is there an update about this?

Thanks

**Comment by ncooke3** [comment]
Hi everyone, yes– those are the two required reason APIs that will be documented. I don't have a release date to share yet, but we will be adding one to this repo soon. I'll keep this thread updated.
