### ISSUE TITLE
issue with Third_party-IsAppEncrypted dependencies name

### ISSUE THREAD

**Issue by sassiwalid** [google/GoogleUtilities#140]
Hello everyone we faced an issue with your last version 7.12.0 that contains a dependency which his name is malformatted and cause a block from Apple when we upload to iTunes Connect.
this is the error 
`Asset validation failed This bundle is invalid. The bundle at path Payload/******/Frameworks/third_party-IsAppEncrypted.framework has an invalid CFBundleIdentifier 'third_party-IsAppEncrypted' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'third\u005fparty-IsAppEncrypted' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] (ID: 7bf7a09b-a8e9-438e-8591-442cd9f73f7e) (90049)
 {
    NSLocalizedDescription = "Asset validation failed";
    NSLocalizedFailureReason = "This bundle is invalid. The bundle at path Payload/AppOfCards.app/Frameworks/third_party-IsAppEncrypted.framework has an invalid CFBundleIdentifier '**third_party-IsAppEncrypted**' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point 'third\\u005fparty-IsAppEncrypted' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105] (ID: 7bf7a09b-a8e9-438e-8591-442cd9f73f7e)";
    NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=This bundle is invalid. The bundle at path Payload/AppOfCards.app/Frameworks/third_party-IsAppEncrypted.framework has an invalid 
}
I resolved the issue by rollback to the 7.11.5 I think that you should update your third_party-IsAppEncrypted.framework  CFBundleIdentifier to respect Apple recommendation

regards

**Comment by ncooke3** [comment]
Thanks for reporting, @sassiwalid! I will look into this.

**Comment by ncooke3** [comment]
Hi @sassiwalid, I released 7.12.1 that contains a fix for this issue. Please let me know if you run into any issues after updating, and I can re-open this bug. Thanks again for the report!

**Comment by sassiwalid** [comment]
thank you great, I will update with this version and I will tell you :)
