### ISSUE TITLE
issue with 7.13 version

### ISSUE THREAD

**Issue by sassiwalid** [google/GoogleUtilities#146]
Hello I think that the 7.13 version has an issue with the Privacy dependency

error: module name "GoogleUtilities-Privacy" is not a valid identifier

which block the upload symbols on Apple platform. Can you please resolve this issue of naming.

regards

**Comment by ncooke3** [comment]
Hi @sassiwalid, is this error appearing when trying to upload to the App Store? If so, which Xcode version are you using?

**Comment by ncooke3** [comment]
@sassiwalid, can you reproduce the issue when selecting _Validate App_ (I've circled the button in the top right of the below image)?
 
<img width="1470" alt="Screenshot 2024-03-04 at 1 01 13 PM" src="https://github.com/google/GoogleUtilities/assets/36927374/6ecc12b3-eca7-41ec-aac0-07857cd175c1">

**Comment by sassiwalid** [comment]
I have validate using the 7.12 or 7.11.5 version using the organizer, no problem but when I launch the CI/CD with the 7.13 version I got the error above

**Comment by ncooke3** [comment]
Interesting, thanks. I wasn't able to reproduce this while validating on Xcode 15.1, Xcode 15.2, or Xcode 15.3. Could you please try validating the 7.13.0 version using the organizer? I'm still trying to narrow down the scope of the issue. I suspect the cause lies in the target containing resources _and_  a dash in its name.

**Comment by sassiwalid** [comment]
Really very strange with organizer upload and the 7.13 version the upload work 
<img width="734" alt="Capture d’écran 2024-03-04 à 20 46 02" src="https://github.com/google/GoogleUtilities/assets/10390684/97d823da-67d3-4581-8956-283d9903d6ea">

But on CI/CD they still not work with the 7.13

**Comment by ncooke3** [comment]
Hi @sassiwalid, I presume your project is using GoogleUtilities via a dependency on Firebase. What version of Firebase are you using? I have a potential fix that I could include in a branch off of the Firebase version you are using so you can test it out.

**Comment by sassiwalid** [comment]
Hello @ncooke3  we use firebase version 10.1.0, and yes under the hood firebase load GoogleUtilities as you have mentioned.

**Comment by ncooke3** [comment]
Hi @sassiwali, I published a point release 7.13.1 with a fix that hopefully will unblock you. Could you please try pulling this new GoogleUtilities version?

**Comment by sassiwalid** [comment]
Yes I will check now

**Comment by MinceMan** [comment]
Note dups
https://youtrack.jetbrains.com/issue/KT-66278/KMP-Cocoapods-dependencies-not-found-with-unexpected-SPM-interaction
https://github.com/firebase/firebase-ios-sdk/issues/12458
https://github.com/google/promises/issues/229

**Comment by Neusoft-Songtn** [comment]
Hello, I saw that the author released release 7.13.1 to solve the above problems, but it seems that the version on Cocoapods platform has not been updated. Our App uses pod for integration, can we update the pod version to 7.13.1? Thank you very much

**Comment by ncooke3** [comment]
Hi @Neusoft-Songtn, this issue was with Swift Package Manager so there was no CocoaPods release for 7.13.1

**Comment by sassiwalid** [comment]
Hello @ncooke3  thank you sorry I'm very late to respond to you. Now it's work great on Ci CD with the last version 7.13.1
