### ISSUE TITLE
Privacy Manifest in it's own bundle causing AppStore Connect issue?

### ISSUE THREAD

**Issue by Jon889** [google/GoogleUtilities#150]
Initially I had several warnings in the App Store Connect email about various APIs that needed warnings, I updated my dependencies to versions that included their privacy manifests. And then the next submission I was left with just one:

> ITMS-91053: Missing API declaration - Your app’s code in the “Elfin” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp

I know I don't use any of the APIs in my own app code. I checked to confirm it's just this library that is needing this category eg using this [here](https://github.com/Wooder/ios_17_required_reason_api_scanner). 

I uploaded a build to App Review without Firebase (and therefore without this library) and didn't get the warning email for ITMS-91053.

I noticed that all the other bundles for privacy manifests in my app bundle are named exactly after the framework/targets, where as this library has it's own bundle for the privacy manifest. 

According to this Apple Engineer here (https://forums.developer.apple.com/forums/thread/742221?answerId=776008022#776008022) each target needs to have its own privacy manifest, so would it be possible to update this library so that each target has its own privacy manifest directly?

(Apologies for not being a Googler, but the issue seems to be directly with this library and not Firebase)

**Comment by Jon889** [comment]
@ncooke3 Really sorry to mention you directly, but as it's May 1st tomorrow which is Apple's deadline, would you be able to take a look at this?

**Comment by paulb777** [comment]
If you haven't yet seen the latest guidance from Apple, see https://developer.apple.com/news/?id=pvszzano. 

The "newly added third-party SDK" clause may have impacted our testing. We'll investigate.

**Comment by ncooke3** [comment]
Hi everyone, this has been addressed in the just released 7.13.3. Thanks for reporting!
