### ISSUE TITLE
Error in iOS app about NSKeyedUnarchiver

### ISSUE THREAD

**Issue by lymancao** [google/GoogleUtilities#153]
iOS 16.4.1
XCode 15.1

When our app startup, I see some error.

> *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x1e169ef58) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSSet' (0x1e16974d8) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.

NSKeyedUnarchiver is used in GULSecureCoding.m

**Comment by paulb777** [comment]
Closing. If the issue recurs. Please open an issue at https://github.com/firebase/firebase-ios-sdk/issues with the template completed.
