### ISSUE TITLE
VisionOS build error

### ISSUE THREAD

**Issue by Vaberer** [google/GoogleUtilities#191]
I'm getting a build error for `HasSCInfoFolder`,  `HasEmbeddedMobileProvision` and `isAppExtension` when building the Firebase project via CocoaPods. is this library updates to support VisionOS?

I"m using Xcode Version 15.4 (15F31d).
GoogleUtilities is used with 7.13.3 version.

![Screenshot 2024-06-17 at 11 47 39](https://github.com/google/GoogleUtilities/assets/8090436/d2cd1bb6-bed3-4cf0-a435-f63d3b17d2d9)

**Comment by paulb777** [comment]
This library and Firebase are only supported for visionOS via Swift Package Manager. 

Please follow https://github.com/firebase/firebase-ios-sdk/issues/13083.

**Comment by Vaberer** [comment]
Looks, there is already a post install script solution how to make CocoaPods work for VisionOS. Since you already have a working solution for SPM, would be possible to port it to CocoaPods?

Thank you.
