### ISSUE TITLE
Request for XCFramework Distribution of GoogleUtilities to Simplify C++ Project Integration

### ISSUE THREAD

**Issue by ezefranca** [google/GoogleUtilities#212]
### Summary
GoogleUtilities is currently distributed as source code, but this causes integration issues with C++ projects that would greatly benefit from old way as XCFramework support.

### Problem
I'm working on a C++ project that requires integration with GoogleUtilities, but the current non-XCFramework distribution is causing headaches during the integration process. 

### Request
Could you please distribute GoogleUtilities (again) as an XCFramework? 

If it's already possible, do you mind to send me how?

Thanks.

**Comment by ncooke3** [comment]
Hi @ezefranca, `GoogleUtilities` is provided as an XCframework in the monthly Firebase release. To access it, download the Firebase.zip under the _Assets_ section of a Firebase GitHub release (here's the latest release: https://github.com/firebase/firebase-ios-sdk/releases/tag/11.2.0). 

Unzip the artifact and the version of the GoogleUtilities SDK will be included in the METADATA.md file. The `GoogleUtilities.xcframework` can be found in the FirebaseAnalytics/ directory of the decompressed zip artifact. The XCFramework is code signed as well. Let me know if you have any questions.
