### ISSUE TITLE
'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0

### ISSUE THREAD

**Issue by saldous** [google/GoogleUtilities#97]
Upgraded GoogleUtilities from 7.9.0 to 7.10.0 and I'm now seeing these warnings in Xcode:

`'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0`

<img width="2183" alt="image" src="https://user-images.githubusercontent.com/3334306/201539547-40405c51-f5e9-44e4-9165-eb11dd24880d.png">

**Comment by paulb777** [comment]
Please share reproduction instructions. GoogleUtilities supports iOS 9.0+, so this warning should not be happening in regular setups.

**Comment by rpendleton** [comment]
I think this is happening because one of Xcode's "recommended settings" upgrades is to update the deployment target to iOS 12.0. If I choose not to update to the recommended settings and just leave the warning there, then the deprecation warning doesn't appear.
